random_navigator:
  ros__parameters:
    # calibrated map‐frame corner coordinates
    top_left:    [ -0.328,  0.576 ]
    top_right:   [  1.07,  0.599 ]
    bottom_right: [  0.977, -0.537 ]
    bottom_left: [ -0.328, -0.411 ]

    # where to place the robot at startup (must match one of the above)
    start_corner: "top_left"
    start_yaw:    0.274        # radians, 0 = facing +x in the map frame

    # how long to wait after setInitialPose() for AMCL to converge
    amcl_wait_time: 2.0      # seconds

    # random‐goal loop settings
    num_random_goals: 10     # total goals to send (omit or set to 0 for infinite)

    # speed limits for navigation (m/s and m/s²)
    max_speed: 0.3
    max_accel: 0.2
